# Generated by Django 5.1 on 2024-08-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
