# Generated by Django 5.1 on 2024-08-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_scrapeddata_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvilableUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
