# Generated by Django 5.1 on 2024-09-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_rename_vacancy_job_source_job_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_posted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
