# Generated by Django 5.1 on 2024-09-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_job_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='avilableurl',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
