# Generated by Django 5.1 on 2024-09-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0014_avilableurl_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='avilableurl',
            name='category',
            field=models.ManyToManyField(blank=True, to='scraper.category'),
        ),
    ]
