# Generated by Django 5.1 on 2024-12-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0023_category_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sub_category',
        ),
    ]
